### ISSUE TITLE
otpResponse returns "OPERATION_NOT_ALLOWED"

### ISSUE THREAD

**Issue by wizpizz** [StarNumber12046/rebeal#2]
On the login page, after entering my phone number and clicking on "Continue", nothing was happening. So, I checked the response to the API request and apparently Google returns the following response:
(Btw, I think it would be useful to show the error message as a pop-up to the user so that they know what's going on)

![LoR_IkKVrqiI1R](https://github.com/user-attachments/assets/ca47c646-4c5b-4a82-bfba-10fc8179ff08)

**Comment by StarNumber12046** [comment]
I can't reproduce this, does it happen with other clients?

Il gio 12 set 2024, 17:37 wizpizz ***@***.***> ha scritto:

**Comment by StarNumber12046** [comment]
If this happens again, I could add token login

**Comment by oenderg** [comment]
> I can't reproduce this, does it happen with other clients?

That was with the released Android APK. I can't retry with another client right now since I get "TOO_MANY_ATTEMPTS_TRY_LATER", now, but I'll give it go later once the ratelimit has cooled off.


> If this happens again, I could add token login

Yeah that would be great

**Comment by StarNumber12046** [comment]
> > I can't reproduce this, does it happen with other clients?
> 
> That was with the released Android APK. I can't retry with another client right now since I get "TOO_MANY_ATTEMPTS_TRY_LATER", now, but I'll give it go later once the ratelimit has cooled off.
> 
> > If this happens again, I could add token login
> 
> Yeah that would be great

hey, did you manage to test if it works with, for example, [beunblurred](https://beunblurred.co)

**Comment by StarNumber12046** [comment]
hey, any updates?

**Comment by ZsoltiHUB** [comment]
Same issue for me, BeUnblurred works, but this app doesn't for some reason

**Comment by StarNumber12046** [comment]
> Same issue for me, BeUnblurred works, but this app doesn't for some reason

Try using token login, copy the tokens from beunblureed cookies (for example from devtools > application > cookies) and paste them there

**Comment by ZsoltiHUB** [comment]
> Try using token login

Thanks for the reply, will try that!
Where can I access the token login option?

**Comment by StarNumber12046** [comment]
> > Try using token login
> 
> Thanks for the reply, will try that! Where can I access the token login option?

hey, I noticed it was a bit broken :/. As soon as the current CI run completes, you can redownload the apk and tap Token Login in the login screen. I hope you enjoy this and it works :)

**Comment by ZsoltiHUB** [comment]
> I hope you enjoy this and it works :)

It works! Thanks again :)

**Comment by StarNumber12046** [comment]
nice
